id: 64c4a261bcdd4c6f93f5fcc919425b02
title: Toh_113-The_White_Lotus_of_the_Good_Dharma-v1
type: translation
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2019-01-29T22:25:18.805Z'
  creationid: BG
  eft-text-id: UT22084-051-001
  eft-text-version: 1.14.0 2020
  xmlns-eft: http://read.84000.co/ns/1.0
